$op = '<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:mix="http://www.jcp.org/jcr/mix/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="cq:Page">
    <jcr:content
        cq:lastModified="***DATE***"
        cq:lastModifiedBy="***username***"
        cq:lastReplicated="***DATE***"
        cq:lastReplicatedBy="***username***"
        cq:lastReplicationAction="Activate"
        cq:template="/apps/canada/templates/page-generic-v2"
        jcr:isCheckedOut="{Boolean}true"
        jcr:language="***langToggle***"
        jcr:lastModified="***DATE***"
        jcr:lastModifiedBy="***username***"
        jcr:mixinTypes="[mix:referenceable,mix:versionable]"
        jcr:primaryType="cq:PageContent"
        jcr:title="***TITLE***"
        jcr:uuid="e601bd63-ed6b-40c2-a13a-744a6f4cbf07"
        sling:redirect="{Boolean}false"
        sling:resourceType="canada/components/structure/page-generic-v2"
        comments="Page generated by D2GC version 1.4"
        gcAltLanguagePeer="***ALTLOC***"
        gcAudience="[gc:audience/general-public]"
        gcContentType="***content-types***"
        gcBranch="***contributor***"
        gcContributor="***contentprovider***"
		gcCreator="[gc:institutions/***aemgc***]"
        gcCredentialEmail="***email***"
        gcCredentialFirstName="***fname***"
        gcCredentialLastName="***lname***"
        gcCredentialUserName="***username***"
        gcDateExpired="{Date}2030-09-01T08:00:00.000-05:00"
        gcDescription="***description***"
        gcFreeSubject="***subject***"
        gcGuid="72251656-5536-4185-8223-ac0ae1bf9669-en"
        gcInstitutionName="[gc:institutions/***aemgc***]"
        gcIssued="{Date}2017-05-15T00:00:00.000-04:00"
        gcKeywords="***keywords***"
        gcLanguage="***lang***"
        gcLicence="Open Government Licence"
        gcModified="***MODOVERDATE***"
        gcModifiedIsOverridden="{Boolean}***OVERRIDE***"
        gcModifiedOverride="***OVERRIDEDATE***"
        gcPageContextTags="***ARCHIVED***"
		gcPrimaryTopic="[gc:themes-and-topics/taxes]"
        gcPublisherOrgName="[gc:institutions/***aemgc***]"
        gcPublisherOrgNameatPublication="[gc:institutions/***aemgc***]"
        gcSpatialCountry="Canada"
        gcGeographicRegionName="[]"
        gcGeographicRegionName_x0040_TypeHint="String[]"
        gcSubject_x0040_TypeHint="String[]"
        limitedWidth="true"
		otherName=""
        otherPath="***ALTLOC***"
        otherTitle="***TITLEFR***">
        <ipar-header
            jcr:primaryType="nt:unstructured"
            sling:resourceType="wcm/foundation/components/iparsys">
            <iparsys_fake_par
                jcr:primaryType="nt:unstructured"
                sling:resourceType="wcm/foundation/components/iparsys/par"/>
        </ipar-header>
        <title
            jcr:lastModified="***DATE***"
            jcr:lastModifiedBy="***username***"
            jcr:primaryType="nt:unstructured"
            sling:resourceType="canada/components/content/mwstitle"
            hideElement="true"
            showbyline="false"
            text="***TEXT***"
            textIsRich="true"/>'
$ed = '<par-right
            jcr:primaryType="nt:unstructured"
            sling:resourceType="foundation/components/parsys"/>
        <ipar-content-footer
            jcr:primaryType="nt:unstructured"
            sling:resourceType="wcm/foundation/components/iparsys">
            <iparsys_fake_par
                jcr:primaryType="nt:unstructured"
                sling:resourceType="wcm/foundation/components/iparsys/par"/>
        </ipar-content-footer>
        <ipar-footer
            jcr:primaryType="nt:unstructured"
            sling:resourceType="wcm/foundation/components/iparsys">
            <iparsys_fake_par
                jcr:primaryType="nt:unstructured"
                sling:resourceType="wcm/foundation/components/iparsys/par"/>
        </ipar-footer>
    </jcr:content>
</jcr:root>'

$parOp = '<par
            jcr:primaryType="nt:unstructured"
            sling:resourceType="foundation/components/parsys">'
$parEd = '</par>'

$hr = '<mwshorizontalrule
                        jcr:created="***DATE***"
                        jcr:createdBy="***username***"
                        jcr:lastModified="***DATE***"
                        jcr:lastModifiedBy="***username***"
                        jcr:primaryType="nt:unstructured"
                        sling:resourceType="canada/components/content/mwshorizontalrule"/>'

$bodyText = '<mwsbodytext
                jcr:created="***DATE***"
                jcr:createdBy="***username***"
                jcr:lastModified="***DATE***"
                jcr:lastModifiedBy="***username***"
                jcr:primaryType="nt:unstructured"
                sling:resourceType="canada/components/content/mwsbodytext"
                text="***TEXT***"
                textIsRich="true"/>'

$genericText = '<mwsgeneric_base_html
                jcr:created="***DATE***"
                jcr:createdBy="***username***"
                jcr:lastModified="***DATE***"
                jcr:lastModifiedBy="***username***"
                jcr:primaryType="nt:unstructured"
                sling:resourceType="canada/components/content/mwsgeneric-base-html"
                text="***TEXT***"/>'

$columnsOp = '<mwscolumns
                jcr:created="***DATE***"
                jcr:createdBy="***username***"
                jcr:lastModified="***DATE***"
                jcr:lastModifiedBy="***username***"
                jcr:primaryType="nt:unstructured"
                sling:resourceType="canada/components/content/mwscolumns"
                colFormat="***SIZE***">'
$columnsEd = '</mwscolumns>'

$panelOp = '<mwspanel
                jcr:created="***DATE***"
                jcr:createdBy="***username***"
                jcr:lastModified="***DATE***"
                jcr:lastModifiedBy="***username***"
                jcr:primaryType="nt:unstructured"
                sling:resourceType="canada/components/content/mwspanel"
                appearance="***CLASS***"
                bodyFormat="default"
                header="***HEADER***"
                hTag="h3"
                text="Add HTML here."
                textIsRich="[true,true]"
                toggle="false">
                <panPar
                    jcr:primaryType="nt:unstructured"
                    sling:resourceType="foundation/components/parsys">'
$panelEd = '</panPar>
            </mwspanel>'

$colOp = '<colpar-***NUMBER***
                    jcr:primaryType="nt:unstructured"
                    sling:resourceType="foundation/components/parsys">'
$colEd = '</colpar-***NUMBER***>'

$ulOp = '<mwsmulti_list
                jcr:created="***DATE***"
                jcr:createdBy="admin"
                jcr:lastModified="***DATE***"
                jcr:lastModifiedBy="admin"
                jcr:primaryType="nt:unstructured"
                sling:resourceType="canada/components/content/mwsmulti-list"
                listFrom="static"
                template="unordered"
                toggle="false"
                ulcss="***ULCLASS***">'

$olOp = '<mwsmulti_list
                jcr:created="***DATE***"
                jcr:createdBy="admin"
                jcr:lastModified="***DATE***"
                jcr:lastModifiedBy="admin"
                jcr:primaryType="nt:unstructured"
                sling:resourceType="canada/components/content/mwsmulti-list"
                listFrom="static"
                olcss="***OLCLASS***"
                template="ordered"
                toggle="false">'

$dlOp = '<mwsmulti_list
                jcr:created="***DATE***"
                jcr:createdBy="admin"
                jcr:lastModified="***DATE***"
                jcr:lastModifiedBy="admin"
                jcr:primaryType="nt:unstructured"
                sling:resourceType="canada/components/content/mwsmulti-list"
                listFrom="static"
                template="***LTEMPLATE***"
                toggle="false">'
$dlEd = '</mwsmulti_list>'

$dtOp = '<list jcr:primaryType="nt:unstructured">'
$dtEd = '</list>'

$dt = '<_x003***1***_***2***
                        jcr:primaryType="nt:unstructured"
                        displayAs="0"
                        link="#"
                        title="***TEXT***"/>'

$dd = '<text***LISTNUM***
                    jcr:lastModified="***DATE***"
                    jcr:lastModifiedBy="admin"
                    jcr:primaryType="nt:unstructured"
                    sling:resourceType="canada/components/content/mwsbodytext"
                    supportingContent="false"
                    text="***TEXT***"
                    textIsRich="true"/>'

$alertOp = '<mwsalerts
                jcr:created="***DATE***"
                jcr:createdBy="admin"
                jcr:lastModified="***DATE***"
                jcr:lastModifiedBy="admin"
                jcr:primaryType="nt:unstructured"
                sling:resourceType="canada/components/content/mwsalerts"
                alerts="1">'


$alert = '<alert-0
                    jcr:lastModified="***DATE***"
                    jcr:lastModifiedBy="admin"
                    jcr:primaryType="nt:unstructured"
                    sling:resourceType="canada/components/content/mwsalert"
                    alertText="***TEXT***"
                    alertTitle="***TITLE***"
                    alertType="***CLASS***"
                    hTag="h2"
                    textIsRich="[true,true]"/>'

$alertEd = '</mwsalerts>'


$opXml = '<?xml version="1.0" encoding="UTF-8"?>
<workspaceFilter version="1.0">'

$edXml = '</workspaceFilter>'
